# Generated by Django 4.0.7 on 2023-03-29 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('CS1 Section 1', 'CS1 Section 1'), ('CS1 Section 2', 'CS1 Section 2'), ('SWE Section 1', 'SWE Section 1')], default='CS1 Section 1', max_length=20)),
                ('taken_prev', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=3)),
                ('prev_desc', models.CharField(default='test', max_length=40)),
                ('resume', models.FileField(upload_to='')),
                ('coverl_desc', models.CharField(default='test', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todolist')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednsday'), ('TH', 'Thursday'), ('F', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('disc_flag', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('disc_section', models.CharField(blank=True, max_length=30)),
                ('office_hours', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=1)),
                ('graded_hw', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('positions', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=1)),
                ('desc', models.CharField(max_length=200)),
                ('applications', models.ManyToManyField(default='', to='main.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
