# Generated by Django 4.0.7 on 2023-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('CS1 Section 1', 'CS1 Section 1'), ('CS1 Section 2', 'CS1 Section 2')], default='CS1 Section 1', max_length=20)),
                ('taken_prev', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=3)),
                ('prev_desc', models.CharField(max_length=40)),
                ('coverl_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
