# Generated by Django 4.0.7 on 2023-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.CharField(default='none', max_length=20, primary_key=True, serialize=False),
        ),
    ]
