# Generated by Django 4.0.7 on 2023-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='applications',
            field=models.ManyToManyField(blank=True, default='', to='main.application'),
        ),
    ]
