# Generated by Django 4.0.7 on 2023-03-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='TEST0000.0: default_code', max_length=60),
        ),
    ]
