# Generated by Django 4.0.7 on 2023-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_prev_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='coverl_desc',
            field=models.CharField(default='', max_length=200),
        ),
    ]
