# Generated by Django 4.0.7 on 2023-03-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
