# Generated by Django 4.0.7 on 2023-03-21 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_admin'),
        ('main', '0007_alter_application_coverl_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('days', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednsday'), ('TH', 'Thursday'), ('F', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('disc_flag', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('disc_section', models.CharField(blank=True, max_length=30)),
                ('office_hours', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=1)),
                ('graded_hw', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('positions', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='2', max_length=1)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
