# Generated by Django 4.0.7 on 2023-03-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_instructor',
        ),
    ]
